# Nombre de la App
spring.application.name=lifeos

# Conexi�n BBDD (Aseg�rate de tener PostgreSQL corriendo y una bbdd llamada 'lifeos_db')
spring.datasource.url=jdbc:postgresql://localhost:5432/lifeos_db
spring.datasource.username=postgres
spring.datasource.password=admin
#spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate (Crea las tablas automticamente)
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Seguridad (Para evitar login por defecto al principio)
 spring.security.user.name=postgres
# spring.security.user.password=admin

#seguridad JWT
app.jwtSecret=nil_3enIwWIub0Z5tgyyji4LUhGQjeoXJt2s2h8g
app.jwtExpirationMs=86400000

# Credenciales del primer administrador 
app.setup.admin.username=admin
app.setup.admin.password=admin123
