# Nombre de la App
spring.application.name=lifeos

# Conexión BBDD (Asegúrate de tener PostgreSQL corriendo y una bbdd llamada 'lifeos_db')
spring.datasource.url=jdbc:postgresql://localhost:5432/lifeos_db
spring.datasource.username=postgres
spring.datasource.password=admin
#spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate (Crea las tablas automáticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Seguridad (Para evitar login por defecto al principio)
 spring.security.user.name=postgres
# spring.security.user.password=admin